### PR TITLE
Inline amd config and start scripts inthe index.html

### PR DESCRIPTION
**Pull request by ffaubry**
This implementation should support two scenarios via the ember-cli-build property amd.inline:
- inline = true (default): the amd config and the amd start scripts will be inlined in the index.html. This is to avoid xhr round trip for bootstrapping the application
- inline = false: the amd config and amd start scripts will be saved in the assets directory and loaded by the index file. 
If the config and start scripts are not inlined then then will be fingerprinted if requested.

### CODE REVIEW

**Comment by jrowlingson** [comment]
Thanks for looking at this!

We are still seeing an issue on livereload rebuilds via ```ember s``` - ```dist/assets/amd-start.js``` goes missing.

**Comment by ffaubry** [comment]
@jrowlingson could you confirm that you are actually not inlining 'inline: false'

**Comment by dbouwman** [comment]
@ffaubry / @jrowlingson / @odoe - qucik test on our app and this is working smoothly

**Comment by ffaubry** [comment]
@jrowlingson I found your issue. Please upgrade and retest. Thx!

**Comment by jrowlingson** [comment]
@ffaubry lgtm

**Comment by ffaubry** [comment]
Thanks to @dbouwman for snowplowing that road. Thanks to @jrowlingson for his help in testing.
Tricky thing to deal with continuous ember build, inlining or not, and fingerprinting.

**Pull request merged**
